/**
 * SEED SCRIPT — Run once to populate MongoDB with existing Flightlanes data.
 *
 * Usage:
 *   1. Add MONGODB_URL to your .env.local
 *   2. Run: node --env-file=.env.local scripts/seed.js
 *
 * This will DELETE all existing airlines/destinations and re-insert them.
 */

import mongoose from 'mongoose';

const MONGODB_URL = process.env.MONGODB_URL;
if (!MONGODB_URL) { console.error('Missing MONGODB_URL'); process.exit(1); }

/* ── Schemas (inline to avoid ESM import issues) ── */
const AirlineSchema = new mongoose.Schema({
  name: String, code: String, slug: { type: String, unique: true }, category: String, badge: String,
  heroImg: String, cardImg: String, about: [String],
  stats: [{ val: String, label: String }], features: [{ icon: String, title: String, desc: String }],
  routes: [{ name: String, freq: String, price: String }], quickInfo: [{ lbl: String, val: String }],
  status: { type: String, default: 'published' },
}, { timestamps: true });

const DestinationSchema = new mongoose.Schema({
  name: String, slug: { type: String, unique: true }, continent: String, region: String, flag: String,
  tagline: String, heroImg: String, cardImg: String, about: [String],
  stats: [{ val: String, label: String }], highlights: [{ icon: String, title: String, desc: String }],
  tips: [String], quickInfo: [{ lbl: String, val: String }],
  status: { type: String, default: 'published' },
}, { timestamps: true });

const Airline = mongoose.models.Airline || mongoose.model('Airline', AirlineSchema);
const Destination = mongoose.models.Destination || mongoose.model('Destination', DestinationSchema);

/* ══════════════════════════════════════════════════════════════
   AIRLINES DATA — all 20 from https://flightlanes.vercel.app/airlines
   ══════════════════════════════════════════════════════════════ */
const airlines = [
  {
    name: 'Delta Air Lines', code: 'DL · SkyTeam Alliance', slug: 'delta-air-lines', category: 'us', badge: 'US Major Carrier',
    heroImg: 'https://images.unsplash.com/photo-1540339832862-474599807836?w=1600&q=90',
    cardImg: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&q=85',
    about: ['Delta Air Lines is one of the world\'s oldest and most trusted airlines, founded in 1925. Headquartered in Atlanta, Georgia, Delta operates one of the world\'s largest airline networks with over 5,000 daily flights to 325+ destinations in 52 countries.', 'Known for its industry-leading on-time performance and customer service, Delta has consistently ranked among the top US carriers. Its SkyMiles loyalty program is one of the most rewarding in the industry, with no blackout dates on award tickets.'],
    stats: [{ val: '5,000+', label: 'Daily Flights' }, { val: '325+', label: 'Destinations' }, { val: '52', label: 'Countries' }],
    features: [{ icon: '🛡', title: 'SkyMiles Rewards', desc: 'Earn miles on every flight with no expiry dates and no blackout award dates' }, { icon: '🍽', title: 'In-flight Dining', desc: 'Complimentary meals and snacks on long-haul flights with premium wine selection' }, { icon: '📶', title: 'Delta Wi-Fi', desc: 'Fast satellite Wi-Fi available on most aircraft for work or entertainment' }, { icon: '💼', title: 'Delta One', desc: 'Fully lie-flat business class seats with direct aisle access on international routes' }, { icon: '🎬', title: 'Seatback Entertainment', desc: 'Personal screens on most aircraft with thousands of movies, shows and music' }, { icon: '🧳', title: 'Baggage Policy', desc: 'First checked bag free for SkyMiles members and credit card holders' }],
    routes: [{ name: 'New York JFK → London LHR', freq: 'Daily · 7h 10m', price: 'from $449' }, { name: 'Atlanta ATL → Paris CDG', freq: 'Daily · 9h 25m', price: 'from $499' }, { name: 'Los Angeles LAX → Tokyo NRT', freq: '4×/week · 11h 30m', price: 'from $699' }, { name: 'New York JFK → Los Angeles LAX', freq: '30+/day · 5h 30m', price: 'from $189' }, { name: 'Atlanta ATL → Cancún CUN', freq: 'Daily · 2h 45m', price: 'from $229' }],
    quickInfo: [{ lbl: 'Alliance', val: 'SkyTeam' }, { lbl: 'Hub', val: 'Atlanta (ATL)' }, { lbl: 'Founded', val: '1925' }, { lbl: 'Fleet Size', val: '900+ aircraft' }, { lbl: 'Loyalty', val: 'SkyMiles' }],
    status: 'published',
  },
  { name: 'American Airlines', code: 'AA · oneworld Alliance', slug: 'american-airlines', category: 'us', badge: 'World\'s Largest', heroImg: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=600&q=85', about: ['The world\'s largest airline by fleet size, connecting 350+ destinations across 60+ countries.'], stats: [{ val: '6,800+', label: 'Daily Flights' }, { val: '350+', label: 'Destinations' }, { val: '60+', label: 'Countries' }], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'oneworld' }, { lbl: 'Hub', val: 'Dallas/Fort Worth (DFW)' }, { lbl: 'Founded', val: '1930' }, { lbl: 'Fleet Size', val: '950+ aircraft' }, { lbl: 'Loyalty', val: 'AAdvantage' }], status: 'published' },
  { name: 'United Airlines', code: 'UA · Star Alliance', slug: 'united-airlines', category: 'us', badge: 'Global Network', heroImg: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=85', about: ['Fly United\'s global network spanning 340+ destinations, with premium Polaris Business Class on long-haul.'], stats: [{ val: '4,900+', label: 'Daily Flights' }, { val: '340+', label: 'Destinations' }, { val: '74', label: 'Countries' }], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'Star Alliance' }, { lbl: 'Hub', val: 'Chicago (ORD)' }, { lbl: 'Founded', val: '1926' }, { lbl: 'Fleet Size', val: '870+ aircraft' }, { lbl: 'Loyalty', val: 'MileagePlus' }], status: 'published' },
  { name: 'Southwest Airlines', code: 'WN', slug: 'southwest-airlines', category: 'us', badge: 'No Hidden Fees', heroImg: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=600&q=85', about: ['No change fees, free bags fly free, and flexible fares — the friendliest way to fly across the US.'], stats: [{ val: '4,000+', label: 'Daily Flights' }, { val: '120+', label: 'Destinations' }, { val: '11', label: 'Countries' }], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'None' }, { lbl: 'Hub', val: 'Dallas Love (DAL)' }, { lbl: 'Founded', val: '1967' }, { lbl: 'Fleet Size', val: '800+ aircraft' }, { lbl: 'Loyalty', val: 'Rapid Rewards' }], status: 'published' },
  { name: 'JetBlue Airways', code: 'B6', slug: 'jetblue-airways', category: 'us', badge: 'Premium Economy', heroImg: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&q=85', about: ['JetBlue\'s Mint business class offers lie-flat seats and farm-to-table dining on select transcontinental routes.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Hub', val: 'New York (JFK)' }, { lbl: 'Founded', val: '1998' }, { lbl: 'Loyalty', val: 'TrueBlue' }], status: 'published' },
  { name: 'Alaska Airlines', code: 'AS · oneworld', slug: 'alaska-airlines', category: 'us', badge: 'West Coast Leader', heroImg: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=85', about: ['Alaska\'s vast West Coast network plus international routes to Mexico, Canada and Central America.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'oneworld' }, { lbl: 'Hub', val: 'Seattle (SEA)' }, { lbl: 'Founded', val: '1932' }, { lbl: 'Loyalty', val: 'Mileage Plan' }], status: 'published' },
  { name: 'Spirit Airlines', code: 'NK', slug: 'spirit-airlines', category: 'budget', badge: 'Ultra Low Cost', heroImg: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=85', about: ['Spirit keeps fares low so you choose only what you need. Great for short hops and budget-conscious travelers.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Hub', val: 'Fort Lauderdale (FLL)' }, { lbl: 'Founded', val: '1983' }, { lbl: 'Loyalty', val: 'Free Spirit' }], status: 'published' },
  { name: 'Frontier Airlines', code: 'F9', slug: 'frontier-airlines', category: 'budget', badge: 'Green Low Cost', heroImg: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=600&q=85', about: ['America\'s greenest airline with ultra-low fares across 100+ US cities.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Hub', val: 'Denver (DEN)' }, { lbl: 'Founded', val: '1994' }, { lbl: 'Loyalty', val: 'Frontier Miles' }], status: 'published' },
  { name: 'British Airways', code: 'BA · oneworld', slug: 'british-airways', category: 'international', badge: 'Flag Carrier UK', heroImg: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=600&q=85', about: ['Premium transatlantic routes from London Heathrow with Club World business class and Executive Club miles.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'oneworld' }, { lbl: 'Hub', val: 'London Heathrow (LHR)' }, { lbl: 'Founded', val: '1974' }, { lbl: 'Loyalty', val: 'Executive Club' }], status: 'published' },
  { name: 'Emirates', code: 'EK', slug: 'emirates', category: 'international', badge: 'World\'s Best Airline', heroImg: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600&q=85', about: ['Experience unmatched luxury with Emirates\' A380 first-class suites, private bars and onboard showers.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Hub', val: 'Dubai (DXB)' }, { lbl: 'Founded', val: '1985' }, { lbl: 'Fleet Size', val: '260+ aircraft' }, { lbl: 'Loyalty', val: 'Skywards' }], status: 'published' },
  { name: 'Air France', code: 'AF · SkyTeam', slug: 'air-france', category: 'international', badge: 'French Elegance', heroImg: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=85', about: ['Fly la compagnie nationale with award-winning cuisine, La Première first class and a global codeshare network.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'SkyTeam' }, { lbl: 'Hub', val: 'Paris CDG' }, { lbl: 'Founded', val: '1933' }, { lbl: 'Loyalty', val: 'Flying Blue' }], status: 'published' },
  { name: 'Lufthansa', code: 'LH · Star Alliance', slug: 'lufthansa', category: 'international', badge: 'German Engineering', heroImg: 'https://images.unsplash.com/photo-1455587734955-081b22074882?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1455587734955-081b22074882?w=600&q=85', about: ['Germany\'s flagship carrier with award-winning First Class and Miles & More rewards.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'Star Alliance' }, { lbl: 'Hub', val: 'Frankfurt (FRA)' }, { lbl: 'Founded', val: '1953' }, { lbl: 'Loyalty', val: 'Miles & More' }], status: 'published' },
  { name: 'ANA', code: 'NH · Star Alliance', slug: 'ana', category: 'international', badge: 'Japanese Hospitality', heroImg: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=85', about: ['All Nippon Airways — Japan\'s largest airline delivering legendary Japanese hospitality on every flight.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'Star Alliance' }, { lbl: 'Hub', val: 'Tokyo (NRT/HND)' }, { lbl: 'Founded', val: '1952' }, { lbl: 'Loyalty', val: 'ANA Mileage Club' }], status: 'published' },
  { name: 'Singapore Airlines', code: 'SQ · Star Alliance', slug: 'singapore-airlines', category: 'international', badge: '5-Star Excellence', heroImg: 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=600&q=85', about: ['Consistently rated the world\'s best airline, Singapore Airlines sets the gold standard for premium travel.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'Star Alliance' }, { lbl: 'Hub', val: 'Singapore (SIN)' }, { lbl: 'Founded', val: '1947' }, { lbl: 'Loyalty', val: 'KrisFlyer' }], status: 'published' },
  { name: 'Cathay Pacific', code: 'CX · oneworld', slug: 'cathay-pacific', category: 'international', badge: 'Asia\'s Premier Hub', heroImg: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=600&q=85', about: ['Based in Hong Kong, Cathay Pacific connects Asia to the world with Business and Premium Economy excellence.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'oneworld' }, { lbl: 'Hub', val: 'Hong Kong (HKG)' }, { lbl: 'Founded', val: '1946' }, { lbl: 'Loyalty', val: 'Asia Miles' }], status: 'published' },
  { name: 'Turkish Airlines', code: 'TK · Star Alliance', slug: 'turkish-airlines', category: 'international', badge: 'Most Countries Flown', heroImg: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&q=85', about: ['Turkish Airlines flies to more countries than any other airline, connecting East and West through Istanbul.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Alliance', val: 'Star Alliance' }, { lbl: 'Hub', val: 'Istanbul (IST)' }, { lbl: 'Founded', val: '1933' }, { lbl: 'Loyalty', val: 'Miles&Smiles' }], status: 'published' },
  { name: 'Ryanair', code: 'FR', slug: 'ryanair', category: 'budget', badge: 'Europe Budget King', heroImg: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=85', about: ['Europe\'s largest low-cost carrier connecting 230+ airports across Europe and North Africa at unbeatable prices.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Hub', val: 'Dublin (DUB)' }, { lbl: 'Founded', val: '1984' }, { lbl: 'Fleet Size', val: '500+ aircraft' }], status: 'published' },
  { name: 'easyJet', code: 'U2', slug: 'easyjet', category: 'budget', badge: 'Orange Low Cost', heroImg: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=85', about: ['easyJet makes European city breaks easy with affordable fares to 150+ destinations from major UK airports.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Hub', val: 'London Luton (LTN)' }, { lbl: 'Founded', val: '1995' }], status: 'published' },
  { name: 'WestJet', code: 'WS', slug: 'westjet', category: 'international', badge: 'Canada\'s Favourite', heroImg: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=600&q=85', about: ['WestJet\'s warm, friendly service connects Canadian cities and popular sun destinations from coast to coast.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Hub', val: 'Calgary (YYC)' }, { lbl: 'Founded', val: '1996' }], status: 'published' },
  { name: 'IndiGo', code: '6E', slug: 'indigo', category: 'budget', badge: 'India\'s Largest', heroImg: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=600&q=85', about: ['IndiGo dominates Indian skies with on-time performance and low fares connecting 100+ Indian destinations.'], stats: [], features: [], routes: [], quickInfo: [{ lbl: 'Hub', val: 'Delhi (DEL)' }, { lbl: 'Founded', val: '2006' }], status: 'published' },
];

/* ══════════════════════════════════════════════════════════════
   DESTINATIONS DATA — all 11 from https://flightlanes.vercel.app/destinations
   ══════════════════════════════════════════════════════════════ */
const destinations = [
  {
    name: 'Tokyo', slug: 'tokyo', continent: 'asia', region: '🇯🇵 Asia · Japan', flag: '🇯🇵', tagline: 'Where Tradition Meets the Future',
    heroImg: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=85',
    about: ['Tokyo is one of the world\'s most captivating cities — a seamless fusion of ancient temples and neon-lit skyscrapers, Michelin-starred restaurants and tiny ramen stalls, serene gardens and frenetic pop culture. The Japanese capital consistently tops global travel rankings for safety, cuisine, cleanliness and sheer variety.', 'From the historic streets of Asakusa and the bamboo groves of Arashiyama to the futuristic Shibuya crossing and the tranquil Imperial Palace East Gardens, Tokyo rewards every kind of traveller.'],
    stats: [{ val: '14M+', label: 'Annual Visitors' }, { val: '13.96M', label: 'Population' }, { val: '★★★★★', label: 'Safety Rating' }],
    highlights: [{ icon: '🏯', title: 'Sensoji Temple', desc: 'Tokyo\'s oldest temple, dating to 628 AD, in the historic Asakusa district' }, { icon: '🍜', title: 'Food Capital', desc: 'More Michelin stars than any other city on Earth — 203 and counting' }, { icon: '🌸', title: 'Cherry Blossoms', desc: 'Ueno Park and Shinjuku Gyoen explode with sakura every late March to April' }, { icon: '🎮', title: 'Pop Culture Hub', desc: 'Akihabara electronics district and Harajuku fashion scene are unmissable' }, { icon: '🗼', title: 'Tokyo Tower', desc: 'The 333-metre landmark offers panoramic views over the entire city' }, { icon: '🛁', title: 'Onsen Retreats', desc: 'Day-trip to Hakone for mountain hot springs with views of Mount Fuji' }],
    tips: ['🗓 Best Time: March–May for cherry blossoms; October–November for autumn foliage.', '🚇 Getting Around: The Tokyo Metro and JR Pass make the city extremely easy to navigate. Get a Suica card on arrival.', '💴 Budget Tip: Convenience stores serve surprisingly delicious and cheap meals. A great sushi lunch can cost as little as ¥500.', '📸 Must-Do: Watch the sunrise from the Shibuya Sky observation deck.'],
    quickInfo: [{ lbl: 'Language', val: 'Japanese' }, { lbl: 'Currency', val: 'JPY (¥)' }, { lbl: 'Time Zone', val: 'JST (UTC+9)' }, { lbl: 'Visa', val: '90-day free (US)' }, { lbl: 'Best Airport', val: 'NRT / HND' }, { lbl: 'Avg Flight', val: '~14h from NYC' }],
    status: 'published',
  },
  { name: 'Paris', slug: 'paris', continent: 'europe', region: '🇫🇷 Europe · France', flag: '🇫🇷', tagline: 'The City of Light, Art & Romance', heroImg: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&q=85', about: ['Paris captivates with iconic landmarks, world-class cuisine, and timeless romance at every turn.'], stats: [{ val: '30M+', label: 'Annual Visitors' }, { val: '2.16M', label: 'Population' }, { val: '★★★★☆', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'French' }, { lbl: 'Currency', val: 'EUR (€)' }, { lbl: 'Time Zone', val: 'CET (UTC+1)' }, { lbl: 'Visa', val: '90-day Schengen (US)' }, { lbl: 'Best Airport', val: 'CDG' }, { lbl: 'Avg Flight', val: '~8h from NYC' }], status: 'published' },
  { name: 'Bali', slug: 'bali', continent: 'asia', region: '🇮🇩 Asia · Indonesia', flag: '🇮🇩', tagline: 'Island of the Gods', heroImg: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=600&q=85', about: ['Bali is a tropical paradise with stunning rice terraces, ancient temples, and world-class surfing.'], stats: [{ val: '6M+', label: 'Annual Visitors' }, { val: '4.3M', label: 'Population' }, { val: '★★★★☆', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'Indonesian' }, { lbl: 'Currency', val: 'IDR' }, { lbl: 'Visa', val: 'VOA 30 days' }, { lbl: 'Best Airport', val: 'DPS' }], status: 'published' },
  { name: 'New York City', slug: 'new-york-city', continent: 'americas', region: '🇺🇸 Americas · United States', flag: '🇺🇸', tagline: 'The City That Never Sleeps', heroImg: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=600&q=85', about: ['New York City is the cultural capital of the world — Broadway, Wall Street, Central Park, and limitless energy.'], stats: [{ val: '66M+', label: 'Annual Visitors' }, { val: '8.3M', label: 'Population' }, { val: '★★★★☆', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'English' }, { lbl: 'Currency', val: 'USD ($)' }, { lbl: 'Time Zone', val: 'EST (UTC-5)' }, { lbl: 'Best Airport', val: 'JFK / EWR' }], status: 'published' },
  { name: 'Dubai', slug: 'dubai', continent: 'middle-east', region: '🇦🇪 Middle East · UAE', flag: '🇦🇪', tagline: 'Where Ambition Meets the Desert', heroImg: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=600&q=85', about: ['Dubai is a city of superlatives — tallest buildings, largest malls, and boldest ambitions.'], stats: [{ val: '16M+', label: 'Annual Visitors' }, { val: '3.5M', label: 'Population' }, { val: '★★★★★', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'Arabic/English' }, { lbl: 'Currency', val: 'AED' }, { lbl: 'Visa', val: '30-day on arrival (US)' }, { lbl: 'Best Airport', val: 'DXB' }], status: 'published' },
  { name: 'London', slug: 'london', continent: 'europe', region: '🇬🇧 Europe · United Kingdom', flag: '🇬🇧', tagline: 'History, Culture & Pubs on Every Corner', heroImg: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=600&q=85', about: ['London blends centuries of history with cutting-edge culture, from the Tower to Shoreditch.'], stats: [{ val: '21M+', label: 'Annual Visitors' }, { val: '9M', label: 'Population' }, { val: '★★★★☆', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'English' }, { lbl: 'Currency', val: 'GBP (£)' }, { lbl: 'Time Zone', val: 'GMT (UTC+0)' }, { lbl: 'Best Airport', val: 'LHR' }], status: 'published' },
  { name: 'Maldives', slug: 'maldives', continent: 'asia', region: '🌊 Indian Ocean · Maldives', flag: '🌊', tagline: 'The Last Paradise on Earth', heroImg: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=85', about: ['Crystal-clear waters, overwater villas, and world-class diving make the Maldives the ultimate luxury escape.'], stats: [{ val: '1.7M+', label: 'Annual Visitors' }, { val: '540K', label: 'Population' }, { val: '★★★★★', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'Dhivehi' }, { lbl: 'Currency', val: 'MVR' }, { lbl: 'Visa', val: '30-day on arrival' }, { lbl: 'Best Airport', val: 'MLE' }], status: 'published' },
  { name: 'Rome', slug: 'rome', continent: 'europe', region: '🇮🇹 Europe · Italy', flag: '🇮🇹', tagline: 'The Eternal City', heroImg: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=85', about: ['Rome is an open-air museum where the Colosseum, Vatican, and cobblestone streets tell 3,000 years of history.'], stats: [{ val: '10M+', label: 'Annual Visitors' }, { val: '2.8M', label: 'Population' }, { val: '★★★★☆', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'Italian' }, { lbl: 'Currency', val: 'EUR (€)' }, { lbl: 'Best Airport', val: 'FCO' }], status: 'published' },
  { name: 'New Zealand', slug: 'new-zealand', continent: 'pacific', region: '🇳🇿 Pacific · New Zealand', flag: '🇳🇿', tagline: 'Adventure Capital of the World', heroImg: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=85', about: ['New Zealand offers breathtaking landscapes from fjords to volcanoes, and the friendliest people on Earth.'], stats: [{ val: '3.9M+', label: 'Annual Visitors' }, { val: '5.1M', label: 'Population' }, { val: '★★★★★', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'English/Māori' }, { lbl: 'Currency', val: 'NZD ($)' }, { lbl: 'Best Airport', val: 'AKL' }], status: 'published' },
  { name: 'Barcelona', slug: 'barcelona', continent: 'europe', region: '🇪🇸 Europe · Spain', flag: '🇪🇸', tagline: 'Gaudí, Beaches & Tapas', heroImg: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=85', about: ['Barcelona is where Gaudí\'s surreal architecture meets Mediterranean beaches and world-class nightlife.'], stats: [{ val: '12M+', label: 'Annual Visitors' }, { val: '1.6M', label: 'Population' }, { val: '★★★★☆', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'Spanish/Catalan' }, { lbl: 'Currency', val: 'EUR (€)' }, { lbl: 'Best Airport', val: 'BCN' }], status: 'published' },
  { name: 'African Safari', slug: 'african-safari', continent: 'africa', region: '🌍 Africa · Kenya / Tanzania', flag: '🌍', tagline: 'The Greatest Wildlife Show on Earth', heroImg: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=90', cardImg: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=85', about: ['Witness the Great Migration, see the Big Five, and experience Africa\'s untamed beauty up close.'], stats: [{ val: '2M+', label: 'Annual Visitors' }, { val: 'Vast', label: 'Territory' }, { val: '★★★★☆', label: 'Safety Rating' }], highlights: [], tips: [], quickInfo: [{ lbl: 'Language', val: 'English/Swahili' }, { lbl: 'Currency', val: 'KES / TZS' }, { lbl: 'Visa', val: 'eVisa required' }, { lbl: 'Best Airport', val: 'NBO / JRO' }], status: 'published' },
];

/* ── Run ── */
async function seed() {
  console.log('Connecting to MongoDB...');
  await mongoose.connect(MONGODB_URL, { bufferCommands: false });
  console.log('Connected.');

  console.log('Clearing existing data...');
  await Airline.deleteMany({});
  await Destination.deleteMany({});

  console.log(`Inserting ${airlines.length} airlines...`);
  await Airline.insertMany(airlines);

  console.log(`Inserting ${destinations.length} destinations...`);
  await Destination.insertMany(destinations);

  console.log('✅ Done! Seeded', airlines.length, 'airlines and', destinations.length, 'destinations.');
  process.exit(0);
}

seed().catch(err => { console.error('Seed failed:', err); process.exit(1); });
